#!/bin/bash

#  fatal-bot starting and controlling script
#  fatalctl

#  Copyright © 2009-2012 Ancestors Soft

#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.

#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.

FATALDIR="$PWD"

[ "$1" = "-pv" ] && "$2" "$FATALDIR/fatal.py" || "$FATALDIR/fatal.py" $*

exit 0