Following commands have been turned off for this groupchat (total: %s):\n\n%s = Для этой конференции были отключены следующие команды (всего: %s):\n\n%s
\nFollowing commands have not been turned off, because they are already turned off (total: %s):\n\n%s = \nСледующие команды не были отключены, поскольку они уже отключены (всего: %s):\n\n%s
\nFollowing commands are not commands (total: %s):\n\n%s = \nПеречисленные ниже команды вообще не команды (всего: %s):\n\n%s
\nFollowing commands you can't turn off (total: %s):\n\n%s = \nСледующие команды отключать вообще нельзя (всего: %s):\n\n%s
Following commands are turned off in this groupchat (total: %s):\n\n%s = В этой конференции отключены следующие команды (всего: %s):\n\n%s
All commands are turned on in this groupchat! = В этой конференции включены все команды!
Following commands have been turned on for this groupchat (total: %s):\n\n%s = Для этой конференции были включены следующие команды (всего: %s):\n\n%s
\nFollowing commands have not been turned on, because they are already turned on (total: %s):\n\n%s = \nСледующие команды не были включены, поскольку они не были отключены (всего: %s):\n\n%s
