This resource does not support quotes numbers! = Данный ресурс не поддерживает номера!
Quote №%s <%s> [page№%s]: \n\n%s = Цитата №%s <%s> [стр.№%s]: \n\n%s
Quote №%s <%s> [page№%s]: \n\n%s\n\nLink: %s = Цитата №%s <%s> [стр.№%s]: \n\n%s\n\nСсылка: %s
Quote №%s: \n\n%s = Цитата №%s: \n\n%s
Cycle quote from bashorg.org has been turned on! = Циклический показ цитат с bashorg.org включен!
Cycle quote from bashorg.org has been turned off! = Циклический показ цитат с bashorg.org отключен!