Result of query from pastebin.com:\n\n%s = Результат запроса с pastebin.com:\n\n%s
Available programming languages for posting (total: %s):\n\n%s. = Доступные языки программирования (всего: %s):\n\n%s.
Value of option "%s" has been set successfully! = Новое значение параметра "%s" успешно установлено!
Value of option "%s" is set to "%s"! = Значение параметра "%s" установлено в "%s"!
Available options to set up (total: 3):\n\n%s. = Доступные для настройки опции (всего: 3):\n\n%s.
Unknown paste Id! = Неизвестный идентификатор поста!
Unknown URL! = Неизвестный URL!