This command you can only use in Telegram! = Эту команду можно использовать только в Telegram!
This command you can only use in jabber! Use /tgaccess for this function! = Эту команду можно использовать только в jabber! Используйте /tgaccess для этих целей!
This video is too big for telegram bot:\n\n%s%s = Это видео слишком большое для телеграм-бота:\n\n%s%s
Forward from %s%s (@%s): = Переслано от %s%s (@%s):
Forward from %s%s: = Переслано от %s%s:
Forward from chat %s: = Переслано из %s:
Forward from chat: %s = Переслано из: %s
